package com.lifttrax.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

/** Hosted JDBC/Postgres provider for user-scoped web training data. */
public final class HostedPostgresTrainingDataStoreProvider implements TrainingDataStoreProvider {
  private final HostedPostgresConfig config;

  public HostedPostgresTrainingDataStoreProvider(HostedPostgresConfig config) throws Exception {
    this.config = config;
    try (Connection connection = openConnection()) {
      initializeSchema(connection);
    }
  }

  public static HostedPostgresTrainingDataStoreProvider fromEnvironment() throws Exception {
    return new HostedPostgresTrainingDataStoreProvider(HostedPostgresConfig.fromEnvironment());
  }

  @Override
  public TrainingDataStore forUser(String ownerUserId) throws Exception {
    String appUserId;
    String lifterProfileId;
    try (Connection connection = openConnection()) {
      appUserId = ensureAppUser(connection, ownerUserId);
      lifterProfileId = ensureDefaultLifterProfile(connection, appUserId, ownerUserId);
    }
    return new HostedPostgresTrainingDataStore(config, ownerUserId, appUserId, lifterProfileId);
  }

  static void initializeSchema(Connection connection) throws SQLException {
    try (Statement statement = connection.createStatement()) {
      statement.execute(
          """
              CREATE TABLE IF NOT EXISTS app_users (
                  id VARCHAR(36) PRIMARY KEY,
                  auth_user_id TEXT NOT NULL UNIQUE,
                  email TEXT,
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
              )
              """);
      statement.execute(
          """
              CREATE TABLE IF NOT EXISTS lifter_profiles (
                  id VARCHAR(36) PRIMARY KEY,
                  owner_user_id VARCHAR(36) NOT NULL REFERENCES app_users(id),
                  display_name TEXT NOT NULL,
                  is_default BOOLEAN NOT NULL DEFAULT FALSE,
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
              )
              """);
      statement.execute(
          """
              CREATE INDEX IF NOT EXISTS idx_lifter_profiles_default_owner
              ON lifter_profiles(owner_user_id, is_default)
              """);
      statement.execute(
          """
              CREATE TABLE IF NOT EXISTS exercise_catalog_entries (
                  id VARCHAR(36) PRIMARY KEY,
                  owner_user_id VARCHAR(36) NOT NULL REFERENCES app_users(id),
                  lifter_profile_id VARCHAR(36) NOT NULL REFERENCES lifter_profiles(id),
                  name TEXT NOT NULL,
                  region TEXT NOT NULL,
                  main_lift TEXT,
                  muscles TEXT NOT NULL DEFAULT '',
                  notes TEXT NOT NULL DEFAULT '',
                  enabled BOOLEAN NOT NULL DEFAULT TRUE,
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  UNIQUE(lifter_profile_id, name)
              )
              """);
      statement.execute(
          """
              CREATE TABLE IF NOT EXISTS executions (
                  web_execution_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  id VARCHAR(36) NOT NULL UNIQUE,
                  lifter_profile_id VARCHAR(36) NOT NULL REFERENCES lifter_profiles(id),
                  catalog_entry_id VARCHAR(36) NOT NULL REFERENCES exercise_catalog_entries(id),
                  performed_on DATE NOT NULL,
                  warmup BOOLEAN NOT NULL DEFAULT FALSE,
                  deload BOOLEAN NOT NULL DEFAULT FALSE,
                  notes TEXT NOT NULL DEFAULT '',
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
              )
              """);
      statement.execute(
          """
              CREATE TABLE IF NOT EXISTS execution_sets (
                  id VARCHAR(36) PRIMARY KEY,
                  execution_id VARCHAR(36) NOT NULL REFERENCES executions(id) ON DELETE CASCADE,
                  set_index INTEGER NOT NULL,
                  metric_kind TEXT NOT NULL,
                  metric_a INTEGER NOT NULL DEFAULT 0,
                  metric_b INTEGER,
                  weight TEXT NOT NULL DEFAULT 'none',
                  rpe REAL,
                  UNIQUE(execution_id, set_index)
              )
              """);
      statement.execute(
          """
              CREATE INDEX IF NOT EXISTS idx_catalog_owner_profile_name
              ON exercise_catalog_entries(owner_user_id, lifter_profile_id, name)
              """);
      statement.execute(
          """
              CREATE INDEX IF NOT EXISTS idx_executions_profile_date
              ON executions(lifter_profile_id, performed_on DESC)
              """);
      statement.execute(
          """
              CREATE TABLE IF NOT EXISTS local_imports (
                  id VARCHAR(36) PRIMARY KEY,
                  target_app_user_id VARCHAR(36) NOT NULL REFERENCES app_users(id),
                  target_lifter_profile_id VARCHAR(36) NOT NULL REFERENCES lifter_profiles(id),
                  source_kind TEXT NOT NULL,
                  source_fingerprint TEXT NOT NULL,
                  source_schema_version INTEGER NOT NULL,
                  lift_count INTEGER NOT NULL,
                  execution_count INTEGER NOT NULL,
                  status TEXT NOT NULL,
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  UNIQUE(target_lifter_profile_id, source_fingerprint)
              )
              """);
      statement.execute(
          """
              CREATE TABLE IF NOT EXISTS local_import_records (
                  id VARCHAR(36) PRIMARY KEY,
                  target_lifter_profile_id VARCHAR(36) NOT NULL REFERENCES lifter_profiles(id),
                  import_id VARCHAR(36) NOT NULL REFERENCES local_imports(id) ON DELETE CASCADE,
                  source_table TEXT NOT NULL,
                  source_id TEXT NOT NULL,
                  target_table TEXT NOT NULL,
                  target_id TEXT NOT NULL,
                  UNIQUE(target_lifter_profile_id, source_table, source_id)
              )
              """);
    }
  }

  static String ensureAppUser(Connection connection, String authUserId) throws SQLException {
    String requiredAuthUserId = requireUserId(authUserId);
    String existing = findAppUserId(connection, requiredAuthUserId);
    if (existing != null) {
      return existing;
    }
    String generated = java.util.UUID.randomUUID().toString();
    try (PreparedStatement statement =
        connection.prepareStatement(
            "INSERT INTO app_users (id, auth_user_id, email) VALUES (?, ?, ?)")) {
      statement.setString(1, generated);
      statement.setString(2, requiredAuthUserId);
      statement.setString(3, "");
      statement.executeUpdate();
      return generated;
    }
  }

  static String ensureDefaultLifterProfile(
      Connection connection, String appUserId, String authUserId) throws SQLException {
    try (PreparedStatement statement =
        connection.prepareStatement(
            """
                SELECT id FROM lifter_profiles
                WHERE owner_user_id = ? AND is_default = TRUE
                """)) {
      statement.setString(1, appUserId);
      try (var rs = statement.executeQuery()) {
        if (rs.next()) {
          return rs.getString("id");
        }
      }
    }
    String generated = java.util.UUID.randomUUID().toString();
    try (PreparedStatement statement =
        connection.prepareStatement(
            """
                INSERT INTO lifter_profiles (id, owner_user_id, display_name, is_default)
                VALUES (?, ?, ?, TRUE)
                """)) {
      statement.setString(1, generated);
      statement.setString(2, appUserId);
      statement.setString(3, requireUserId(authUserId));
      statement.executeUpdate();
      return generated;
    }
  }

  static Connection openConnection(HostedPostgresConfig config) throws SQLException {
    Properties properties = new Properties();
    if (!config.username().isBlank()) {
      properties.setProperty("user", config.username());
    }
    if (!config.password().isBlank()) {
      properties.setProperty("password", config.password());
    }
    return DriverManager.getConnection(config.jdbcUrl(), properties);
  }

  private Connection openConnection() throws SQLException {
    return openConnection(config);
  }

  private static String findAppUserId(Connection connection, String authUserId)
      throws SQLException {
    try (PreparedStatement statement =
        connection.prepareStatement("SELECT id FROM app_users WHERE auth_user_id = ?")) {
      statement.setString(1, authUserId);
      try (var rs = statement.executeQuery()) {
        return rs.next() ? rs.getString("id") : null;
      }
    }
  }

  private static String requireUserId(String userId) {
    if (userId == null || userId.isBlank()) {
      throw new IllegalArgumentException("Authenticated user is required.");
    }
    return userId.trim();
  }
}
