CREATE TABLE IF NOT EXISTS app_users (
    id VARCHAR(36) PRIMARY KEY,
    auth_user_id TEXT NOT NULL UNIQUE,
    email TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lifter_profiles (
    id VARCHAR(36) PRIMARY KEY,
    owner_user_id VARCHAR(36) NOT NULL REFERENCES app_users(id),
    display_name TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_lifter_profiles_default_owner
    ON lifter_profiles(owner_user_id, is_default);

CREATE TABLE IF NOT EXISTS exercise_catalog_entries (
    id VARCHAR(36) PRIMARY KEY,
    owner_user_id VARCHAR(36) NOT NULL REFERENCES app_users(id),
    lifter_profile_id VARCHAR(36) NOT NULL REFERENCES lifter_profiles(id),
    name TEXT NOT NULL,
    region TEXT NOT NULL,
    main_lift TEXT,
    muscles TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(lifter_profile_id, name)
);

CREATE TABLE IF NOT EXISTS executions (
    web_execution_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id VARCHAR(36) NOT NULL UNIQUE,
    lifter_profile_id VARCHAR(36) NOT NULL REFERENCES lifter_profiles(id),
    catalog_entry_id VARCHAR(36) NOT NULL REFERENCES exercise_catalog_entries(id),
    performed_on DATE NOT NULL,
    warmup BOOLEAN NOT NULL DEFAULT FALSE,
    deload BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS execution_sets (
    id VARCHAR(36) PRIMARY KEY,
    execution_id VARCHAR(36) NOT NULL REFERENCES executions(id) ON DELETE CASCADE,
    set_index INTEGER NOT NULL,
    metric_kind TEXT NOT NULL,
    metric_a INTEGER NOT NULL DEFAULT 0,
    metric_b INTEGER,
    weight TEXT NOT NULL DEFAULT 'none',
    rpe REAL,
    UNIQUE(execution_id, set_index)
);

CREATE INDEX IF NOT EXISTS idx_catalog_owner_profile_name
    ON exercise_catalog_entries(owner_user_id, lifter_profile_id, name);

CREATE INDEX IF NOT EXISTS idx_executions_profile_date
    ON executions(lifter_profile_id, performed_on DESC);

CREATE TABLE IF NOT EXISTS local_imports (
    id VARCHAR(36) PRIMARY KEY,
    target_app_user_id VARCHAR(36) NOT NULL REFERENCES app_users(id),
    target_lifter_profile_id VARCHAR(36) NOT NULL REFERENCES lifter_profiles(id),
    source_kind TEXT NOT NULL,
    source_fingerprint TEXT NOT NULL,
    source_schema_version INTEGER NOT NULL,
    lift_count INTEGER NOT NULL,
    execution_count INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(target_lifter_profile_id, source_fingerprint)
);

CREATE TABLE IF NOT EXISTS local_import_records (
    id VARCHAR(36) PRIMARY KEY,
    target_lifter_profile_id VARCHAR(36) NOT NULL REFERENCES lifter_profiles(id),
    import_id VARCHAR(36) NOT NULL REFERENCES local_imports(id) ON DELETE CASCADE,
    source_table TEXT NOT NULL,
    source_id TEXT NOT NULL,
    target_table TEXT NOT NULL,
    target_id TEXT NOT NULL,
    UNIQUE(target_lifter_profile_id, source_table, source_id)
);
